# Site settings
title: 花花熊
email: yuhuidev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  花花熊.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://huahuaxiong.com" # the base hostname & protocol for your site
twitter_username: ''
github_username:  huahuaxiong

# Build settings
markdown: kramdown
